trainer:
  target: lightning.pytorch.trainer.Trainer
  devices: all
  max_steps: -1
  check_val_every_n_epoch: 1
  val_check_interval: 64
  log_every_n_steps: 10
  num_sanity_val_steps: 2
  # gradient_clip_val: 1.0
  reload_dataloaders_every_n_epochs: 0
  accumulate_grad_batches: 1  # Reduce to debug hanging issue
  precision: bf16-mixed
  use_distributed_sampler: True
  strategy: auto

  logger:
    target: lightning.pytorch.loggers.WandbLogger
    project: colar-experiments
    name:
    save_dir:

callbacks:
  - target: lightning.pytorch.callbacks.ModelCheckpoint
    save_last: True
    save_top_k: 1
    # mode: max
    mode: min
    monitor: monitor
    auto_insert_metric_name: False
    filename: "epoch{epoch}__step{step}__monitor{monitor:.3f}"
    save_weights_only: True
